<script setup lang="ts">
import AppIcon from './AppIcon.vue'

defineProps<{ open: boolean }>()
defineEmits<{ close: [] }>()
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="tp-modal-backdrop" @click.self="$emit('close')">
      <div class="vf-card tp-modal" role="dialog" aria-modal="true" aria-labelledby="methodology-title">
        <div class="vf-row" style="justify-content: space-between; align-items: flex-start">
          <h3 id="methodology-title" class="vf-headline-md">Methodology</h3>
          <button
            type="button"
            class="vf-btn vf-btn--icon"
            aria-label="Close methodology"
            @click="$emit('close')"
          >
            <AppIcon name="x" :size="18" />
          </button>
        </div>
        <p class="vf-body-md" style="color: var(--vf-muted)">
          <strong style="color: var(--vf-on-surface)">This is a portfolio case study.</strong>
          Two Peaks, Four Seasons uses invented, internally consistent data — no real utility,
          city, or ratepayer data is used anywhere in this project.
        </p>
        <p class="vf-body-md" style="color: var(--vf-muted)">
          Hourly load curves are generated from simplified seasonal models of residential,
          commercial, and industrial demand, combined with illustrative solar generation and EV
          charging curves. The "AI insight" panels are pre-written explainer copy designed to
          demonstrate how an AI-assisted breakdown could sit alongside a chart — they are not
          generated by a live model against real telemetry.
        </p>
        <p class="vf-body-md" style="color: var(--vf-muted)">
          Trend and projection figures (risk-window months, solar/EV adoption) are directional
          and meant to illustrate a plausible trajectory, not a forecast for any real grid.
        </p>
        <button type="button" class="vf-btn vf-btn--primary vf-btn--full" @click="$emit('close')">
          Got it
        </button>
      </div>
    </div>
  </Teleport>
</template>
